export const deniedBuiltins = [
  "Bash",
  "Read",
  "Write",
  "Edit",
  "MultiEdit",
  "Glob",
  "Grep",
  "WebFetch",
  "WebSearch",
  "Task",
  "Agent",
  "NotebookEdit",
  "Computer",
  // Additional built-ins observed in CodeBuddy 0.3.268 iOA initialization.
  "PowerShell",
  "EnterPlanMode",
  "ExitPlanMode",
  "TaskCreate",
  "TaskGet",
  "TaskUpdate",
  "TaskList",
  "TaskStop",
  "TaskOutput",
  "Skill",
  "AskUserQuestion",
  "AskUserForStructuredInput",
  "StructuredOutput",
  "ToolSearch",
  "DeferExecuteTool",
  "SendMessage",
  "SendUserMessage",
  "TeamCreate",
  "TeamDelete",
  "LSP",
  "ImageGen",
  "LibraryUpload",
  "ImageEdit",
  "Artifact",
  "ArtifactControl",
  "VideoGen",
  "AudioTranscribe",
  "EnterWorktree",
  "LeaveWorktree",
  "CronCreate",
  "CronDelete",
  "CronList",
  "WeChatReply",
  "WeComReply",
  "PushNotification",
  "ReportFindings",
  "ComputerUse",
  "ListMcpResources",
  "ReadMcpResource",
  "WaitForMcpServers",
  "Workflow",
  "Monitor",
  "REPL",
  "A2AGetAgentCard",
  "A2ASendMessage",
  "A2AGetTask",
  "A2ACancelTask",
  "MessageColleague",
  "SpeakInChannel",
  "ChannelTasks",
  "CreateColleague",
  "CreateChannel",
  "ListColleagues",
];
export async function secretaryToolPermission(
  name: string,
  args: Record<string, unknown>,
) {
  return /^mcp__secretary__[a-zA-Z0-9_-]+$/.test(name)
    ? { behavior: "allow" as const, updatedInput: args }
    : {
        behavior: "deny" as const,
        message: "Only configured catbot plugin tools are available.",
      };
}
